backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{id}}/index"
    fields:
      - { name: id, label: Id }
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: date, label: Date, widget: datetime }
      - { name: author, label: author }
      - { name: CardImage, label: CardImage, widget: image }
      - { name: CardDesc, label: CardDesc }
      - { name: Image, label: image, widget: image }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
